# Generated by Django 5.1.2 on 2024-10-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_sustain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bc_email',
            field=models.EmailField(default='default@bc.edu', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='minor1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='minor2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
