# Generated by Django 5.1.2 on 2024-10-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bc_sustain', '0003_rename_user_profile_username_profile_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='major1',
            new_name='major',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='major2',
            new_name='minor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='minor1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='minor2',
        ),
    ]
