# Generated by Django 5.1.2 on 2024-10-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc_sustain', '0005_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
