# Generated by Django 5.1.2 on 2024-10-21 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bc_email', models.EmailField(default='default@bc.edu', max_length=254, unique=True)),
                ('school', models.CharField(choices=[('CSOM', 'CSOM'), ('MCAS', 'MCAS'), ('LSEHD', 'LSEHD'), ('CSON', 'CSON'), ('LAW', 'LAW')], max_length=100)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('major', models.CharField(max_length=100)),
                ('minor', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
