# Generated by Django 5.1.2 on 2024-12-01 04:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_points_update",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="profile",
            name="rank_change",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="total_points",
            field=models.IntegerField(default=0),
        ),
    ]
