# Generated by Django 5.1.2 on 2024-12-02 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("article_url", models.URLField(blank=True, max_length=500, null=True)),
                ("date_begin", models.DateField()),
                ("date_end", models.DateField()),
                ("time_begin", models.TimeField()),
                ("time_end", models.TimeField()),
                ("question_1", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "q1_false_answer_1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q1_false_answer_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q1_correct_answer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("question_2", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "q2_false_answer_1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q2_false_answer_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q2_correct_answer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("question_3", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "q3_false_answer_1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q3_false_answer_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "q3_correct_answer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
