# Generated by Django 5.1.2 on 2024-12-02 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailytask',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='weeklytask',
            name='completion_criteria',
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='is_static',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='date_created',
        ),
    ]
