# Generated by Django 5.1.3 on 2024-12-03 09:51

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date_created', models.DateField()),
                ('time_created', models.TimeField()),
                ('points', models.IntegerField(default=0)),
                ('is_redeem', models.BooleanField(default=False)),
                ('location', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Lower', 'Lower'), ('McElroy', 'McElroy'), ('Stuart', 'Stuart'), ("Addie's", "Addie's"), ("Eagle's Nest", "Eagle's Nest")], max_length=41, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
