# Generated by Django 5.1.2 on 2024-12-02 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_dailytask_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
