# Generated by Django 5.1.3 on 2024-12-03 15:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailytask',
            unique_together={('user', 'title', 'is_static', 'completion_criteria')},
        ),
    ]
