# Generated by Django 5.1.2 on 2024-12-03 00:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_dailytask_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailytask',
            unique_together={('user', 'title', 'is_static', 'completion_criteria')},
        ),
        migrations.AddField(
            model_name='dailytask',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='weeklytask',
            name='completion_criteria',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='is_static',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='created_at',
        ),
    ]
