# Generated by Django 5.1.2 on 2024-10-26 23:23

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_campaign_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='location',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Lower', 'Lower'), ('McElroy', 'McElroy'), ('Stuart', 'Stuart'), ("Addie's", "Addie's"), ("Eagle's Nest", "Eagle's Nest")], default=list, max_length=41),
        ),
        migrations.AddField(
            model_name='campaign',
            name='news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='validation',
            field=models.CharField(choices=[('photo validation', 'photo validation'), ('QR', 'QR')], default='photo validation', max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
    #whoops accidentally didn't push this 
    
