# Generated by Django 5.1.2 on 2024-12-03 03:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_dailytask_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='time_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
