# Generated by Django 5.1.2 on 2024-12-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_dailytask_date_created_dailytask_time_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytask',
            name='time_submitted',
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
