# Generated by Django 5.1.2 on 2024-12-03 00:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_dailytask_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
