# Generated by Django 5.1.2 on 2024-12-08 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_referraltempstore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referraltempstore',
            old_name='session_key',
            new_name='username',
        ),
    ]
