# Generated by Django 5.1.2 on 2024-11-01 00:31

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0005_news_profile_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="previous_rank",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="location",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Lower", "Lower"),
                    ("McElroy", "McElroy"),
                    ("Stuart", "Stuart"),
                    ("Addie's", "Addie's"),
                    ("Eagle's Nest", "Eagle's Nest"),
                ],
                max_length=41,
            ),
        ),
    ]
