# Generated by Django 5.1.2 on 2024-12-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_remove_dailytask_time_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='streak_status',
            field=models.IntegerField(default=0),
        ),
    ]
