# Generated by Django 5.1.2 on 2024-10-31 15:03

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_news_profile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='location',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Lower', 'Lower'), ('McElroy', 'McElroy'), ('Stuart', 'Stuart'), ("Addie's", "Addie's"), ("Eagle's Nest", "Eagle's Nest")], max_length=41),
        ),
    ]
