# Generated by Django 5.1.2 on 2024-11-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_campaign_location'),
        ('mainApp', '0006_profile_previous_rank_alter_campaign_location'),
    ]

    operations = [
    ]
