# Generated by Django 5.1.2 on 2024-11-03 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0008_alter_profile_major_alter_profile_minor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="title",
            new_name="display_title",
        ),
        migrations.RemoveField(
            model_name="news",
            name="description",
        ),
        migrations.AddField(
            model_name="news",
            name="date_begin",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="news",
            name="date_end",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="news",
            name="external_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="time_begin",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="news",
            name="time_end",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
