# Generated by Django 5.1.2 on 2024-11-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0010_alter_news_date_begin_alter_news_date_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="news_image",
            field=models.ImageField(blank=True, null=True, upload_to="news_pics/"),
        ),
    ]
