# Generated by Django 5.1.2 on 2024-11-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0011_news_news_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="image",
        ),
        migrations.AlterField(
            model_name="news",
            name="news_image",
            field=models.ImageField(blank=True, null=True, upload_to="news_images/"),
        ),
    ]
