# Generated by Django 5.1.2 on 2024-11-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0012_remove_news_image_alter_news_news_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="news",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="display_title",
            field=models.CharField(max_length=500),
        ),
    ]
