# Generated by Django 5.1.2 on 2024-11-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_dailytask_referraltask_weeklytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='is_satic',
            field=models.BooleanField(default=True),
        ),
    ]
