# Generated by Django 5.1.2 on 2024-11-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_dailytask_is_satic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytask',
            old_name='is_satic',
            new_name='is_static',
        ),
    ]
