# Generated by Django 5.1.2 on 2024-11-21 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_referraltask_completion_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referraltask',
            old_name='points_awarded',
            new_name='points',
        ),
    ]
